language: java

jdk:
  - openjdk8
  - openjdk11

addons:
  apt:
    packages:
      - libxml2-utils

before_install:
  - >
    openssl aes-256-cbc -K $encrypted_1da62148018a_key -iv $encrypted_1da62148018a_iv \
      -in src/main/resources/build-key.gpg.enc -out build-key.gpg -d

install:
  - >
    mvn -s freelib-resources/src/main/resources/settings.xml install -q -DskipTests=true \
      -Dmaven.javadoc.skip=true -B -V

script:
  - .travis/tests

after_success:
  - freelib-resources/src/main/resources/travis/deploy

# The only branch we build on is main; all other builds are done on PRs to main
branches:
  only:
  - main

notifications:
  pushover:
    api_key: "${PUSHOVER_API_KEY}"
    users:
      - "${PUSHOVER_USER_KEY}"
    template: "%{repository_slug} (%{commit}) : %{message} - Build details: %{build_url}"
    on_success: never
    on_failure: change

sudo: false
