language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - libxml2-utils

before_install:
  - >
    openssl aes-256-cbc -K $encrypted_c39593dffbcc_key -iv $encrypted_c39593dffbcc_iv \
      -in src/main/resources/build-key.gpg.enc -out src/main/resources/build-key.gpg -d

install:
  - mvn install -q -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - xmllint --noout freelib-resources/src/main/resources/checkstyle/checkstyle.xml
  - xmllint --noout freelib-resources/src/main/resources/checkstyle/checkstyle-suppressions.xml
  - mvn -q install
  - export JAR_VERSION=$(.travis/get_version)
  - echo "Testing resource packaging for ${JAR_VERSION}"
  - unzip -qq -o -d freelib-resources/target/zipout "freelib-resources/target/freelib-resources-${JAR_VERSION}.jar"
  - echo "Unpacked resources successfully"
  - test "0" -eq $([ -f freelib-resources/target/zipout/checkstyle/checkstyle.xml ] && echo "0" || echo "1")
  - test "0" -eq $([ -f freelib-resources/target/zipout/checkstyle/checkstyle-suppressions.xml ] && echo "0" || echo "1")

after_success:
- freelib-resources/src/main/resources/travis/deploy

notifications:
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: change
    on_success: change

sudo: false
