language: java

jdk:
  - openjdk8
  - openjdk11

addons:
  apt:
    packages:
      - libxml2-utils

before_install:
  - >
    openssl aes-256-cbc -K $encrypted_c39593dffbcc_key -iv $encrypted_c39593dffbcc_iv \
      -in src/main/resources/build-key.gpg.enc -out src/main/resources/build-key.gpg -d

install:
  - mvn install -q -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - .travis/tests

after_success:
  - freelib-resources/src/main/resources/travis/deploy

# The only branch we build on is master; all other builds are done on PRs to master
branches:
  only:
  - master

notifications:
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: change
    on_success: change

sudo: false
