language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script:
  - xmllint --valid --noout freelib-resources/src/main/resources/checkstyle/checkstyle.xml
  - xmllint --valid --noout freelib-resources/src/main/resources/checkstyle/checkstyle-suppressions.xml
  - mvn install
  - unzip -d freelib-resources/target/zipout freelib-resources/target/freelib-resources-`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version |grep -Ev '(^\[|Download\w+:)'`.jar
  - test "0" == $([ -f freelib-resources/target/zipout/checkstyle/checkstyle.xml ] && echo "0" || echo "1")
  - test "0" == $([ -f freelib-resources/target/zipout/checkstyle/checkstyle-suppressions.xml ] && echo "0" || echo "1")

notifications:
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: change
    on_success: change

sudo: false
